//Definicion del modelo de formas de pago!
var mongoose = require('mongoose');
var winston			= require('winston');

var paisesSchema = mongoose.Schema({
	nombre: String
});

var pais = mongoose.model('paises', paisesSchema);

/******************* SERVICIO REST PARA CONSULTAS DE APLICACION WEB! =) *******************/
module.exports.obtenerPaises = function(req, res) {
	pais.find()
		.sort({nombre:1})
		.exec(function(err, data){
		    if (err){
		    	res.send(err);
		    }
		    
		    res.json(data); 
		});
};

module.exports.crear = function(req, res){
	var arrayPais = ["Australia",
					"China",
					"Japan",
					"Thailand",
					"India",
					"Malaysia",
					"Kore",
					"Hong Kong",
					"Taiwan",
					"Philippines",
					"Vietnam",
					"France",
					"Europe",
					"Germany",
					"Sweden",
					"Italy",
					"Greece",
					"Spain",
					"Austria",
					"United Kingdom",
					"Netherlands",
					"Belgium",
					"Switzerland",
					"United Arab Emirates",
					"Israel",
					"Ukraine",
					"Russian Federation",
					"Kazakhstan",
					"Portugal",
					"Saudi Arabia",
					"Denmark",
					"Ira",
					"Norway",
					"United States",
					"Mexico",
					"Canada",
					"Anonymous Proxy",
					"Syrian Arab Republic",
					"Cyprus",
					"Czech Republic",
					"Iraq",
					"Turkey",
					"Romania",
					"Lebanon",
					"Hungary",
					"Georgia",
					"Brazil",
					"Azerbaijan",
					"Satellite Provider",
					"Palestinian Territory",
					"Lithuania",
					"Oman",
					"Slovakia",
					"Serbia",
					"Finland",
					"Iceland",
					"Bulgaria",
					"Slovenia",
					"Moldov",
					"Macedonia",
					"Liechtenstein",
					"Jersey",
					"Poland",
					"Croatia",
					"Bosnia and Herzegovina",
					"Estonia",
					"Latvia",
					"Jordan",
					"Kyrgyzstan",
					"Reunion",
					"Ireland",
					"Libya",
					"Luxembourg",
					"Armenia",
					"Virgin Island",
					"Yemen",
					"Belarus",
					"Gibraltar",
					"Martinique",
					"Panama",
					"Dominican Republic",
					"Guam",
					"Puerto Rico",
					"Virgin Island",
					"Mongolia",
					"New Zealand",
					"Singapore",
					"Indonesia",
					"Nepal",
					"Papua New Guinea",
					"Pakistan",
					"Asia/Pacific Region",
					"Bahamas",
					"Saint Lucia",
					"Argentina",
					"Bangladesh",
					"Tokelau",
					"Cambodia",
					"Macau",
					"Maldives",
					"Afghanistan",
					"New Caledonia",
					"Fiji",
					"Wallis and Futuna",
					"Qatar",
					"Albania",
					"Belize",
					"Uzbekistan",
					"Kuwait",
					"Montenegro",
					"Peru",
					"Bermuda",
					"Curacao",
					"Colombia",
					"Venezuela",
					"Chile",
					"Ecuador",
					"South Africa",
					"Isle of Man",
					"Bolivia",
					"Guernsey",
					"Malta",
					"Tajikistan",
					"Seychelles",
					"Bahrain",
					"Egypt",
					"Zimbabwe",
					"Liberia",
					"Kenya",
					"Ghana",
					"Nigeria",
					"Tanzani",
					"Zambia",
					"Madagascar",
					"Angola",
					"Namibia",
					"Cote D''Ivoire",
					"Sudan",
					"Cameroon",
					"Malawi",
					"Gabon",
					"Mali",
					"Benin",
					"Chad",
					"Botswana",
					"Cape Verde",
					"Rwanda",
					"Congo",
					"Uganda",
					"Mozambique",
					"Gambia",
					"Lesotho",
					"Mauritius",
					"Morocco",
					"Algeria",
					"Guinea",
					"Cong",
					"Swaziland",
					"Burkina Faso",
					"Sierra Leone",
					"Somalia",
					"Niger",
					"Central African Republic",
					"Togo",
					"Burundi",
					"Equatorial Guinea",
					"South Sudan",
					"Senegal",
					"Mauritania",
					"Djibouti",
					"Comoros",
					"British Indian Ocean Territory",
					"Tunisia",
					"Greenland",
					"Holy See (Vatican City State)",
					"Costa Rica",
					"Cayman Islands",
					"Jamaica",
					"Guatemala",
					"Marshall Islands",
					"Antarctica",
					"Barbados",
					"Aruba",
					"Monaco",
					"Anguilla",
					"Saint Kitts and Nevis",
					"Grenada",
					"Paraguay",
					"Montserrat",
					"Turks and Caicos Islands",
					"Antigua and Barbuda",
					"Tuvalu",
					"French Polynesia",
					"Solomon Islands",
					"Vanuatu",
					"Eritrea",
					"Trinidad and Tobago",
					"Andorra",
					"Haiti",
					"Saint Helena",
					"Micronesi",
					"El Salvador",
					"Honduras",
					"Uruguay",
					"Sri Lanka",
					"Western Sahara",
					"Christmas Island",
					"Samoa",
					"Suriname",
					"Cook Islands",
					"Kiribati",
					"Niue",
					"Tonga",
					"French Southern Territories",
					"Mayotte",
					"Norfolk Island",
					"Brunei Darussalam",
					"Turkmenistan",
					"Pitcairn Islands",
					"San Marino",
					"Aland Islands",
					"Faroe Islands",
					"Svalbard and Jan Mayen",
					"Cocos (Keeling) Islands",
					"Nauru",
					"South Georgia and the South Sandwich Islands",
					"United States Minor Outlying Islands",
					"Guinea-Bissau",
					"Palau",
					"American Samoa",
					"Bhutan",
					"French Guiana",
					"Guadeloupe",
					"Saint Martin",
					"Saint Vincent and the Grenadines",
					"Saint Pierre and Miquelon",
					"Saint Barthelemy",
					"Dominica",
					"Sao Tome and Principe",
					"Kore",
					"Islas Malvinas",
					"Northern Mariana Islands",
					"Timor-Leste",
					"Bonair",
					"Myanmar",
					"Nicaragua",
					"Sint Maarten (Dutch part)",
					"Guyana",
					"Lao People''s Democratic Republic",
					"Cuba",
					"Ethiopia"];
	for (var i = 0; i < arrayPais.length; i++) {
			var auxPais = new pais({
							nombre: arrayPais[i]
						});
		
		auxPais.save(function(err, data){
			if(err){
				winston.error("Error generando pais: ");
				winston.error(err);
			}
		});
	};
	
	res.json(arrayPais);
};

/******************* SERVICIO REST PARA CONSULTAS DE APLICACION MOBILE! =) *******************/
module.exports.paises = function(req, res){
	pais.find(function(err, data) {
		if (err){
			winston.error("Error: " + err);
		}
		else{
			winston.debug("Paises: " + data);
			res.json(data);
		}
    });
};